/*
 * main.c - Nodal Runtime Entry Point (V1.0-alpha)
 * Demonstrates the full lifecycle: Load -> Map -> Execute
 */

#include <stdio.h>
#include <stdlib.h>
#include "nodal.h"

/* Forward declarations for functions defined in other files */
extern void* nodal_load_model_mapped(const char *path, nodal_buffer_t *out_runtime, uint32_t max_tensors);
extern void nodal_execute_tape(const nodal_irop_t *ops, size_t op_count, const nodal_buffer_t *tensor_runtime);

/* Kernel prototypes (usually in a header, but placed here for simulation) */
void nodal_kernel_matmul_generic(const nodal_call_t *call);

int main(int argc, char *argv[]) {
    printf("--- Nodal Runtime V1.0-alpha ---\n");

    if (argc < 2) {
        printf("Usage: %s <model.nbbin>\n", argv[0]);
        printf("Note: For initial testing, ensure a valid .nbbin is present.\n");
        // We continue with a mock setup for demonstration if no file provided
    }

    // 1. Allocate the Runtime Tensor Table (The Arena-based pointer list)
    // For this alpha, we support up to 1024 tensors per model.
    uint32_t max_tensors = 1024;
    nodal_buffer_t *tensor_runtime = (nodal_buffer_t *)calloc(max_tensors, sizeof(nodal_buffer_t));

    // 2. Map the Model
    if (argc >= 2) {
        void *model_base = nodal_load_model_mapped(argv[1], tensor_runtime, max_tensors);
        if (!model_base) {
            fprintf(stderr, "Critical: Failed to map model %s\n", argv[1]);
            return EXIT_FAILURE;
        }
        printf("[SUCCESS] Model mapped to memory.\n");
    } else {
        printf("[INFO] No model file provided. Skipping loader...\n");
    }

    // 3. Define a Mock IR Tape (Simulating a single MatMul)
    // In a real scenario, this 'tape' is generated by the Nodal Compiler (nc)
    nodal_irop_t mock_tape[1];
    mock_tape[0].kind = OP_MATMUL;
    mock_tape[0].num_inputs = 2;
    mock_tape[0].num_outputs = 1;
    mock_tape[0].inputs[0] = 0; // Tensor ID 0
    mock_tape[0].inputs[1] = 1; // Tensor ID 1
    mock_tape[0].outputs[0] = 2; // Tensor ID 2

    printf("[INFO] Starting execution tape...\n");
    
    /* * nodal_execute_tape(mock_tape, 1, tensor_runtime); 
     * (Commented out until kernels are registered in executor.c)
     */

    printf("[SUCCESS] Inference cycle complete.\n");

    free(tensor_runtime);
    return EXIT_SUCCESS;
}

